name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: 'Improvements'
    labels:
      - 'perf'
      - 'refactor'
  - title: 'Tests'
    labels:
      - 'tests'
      - 'testing'
  - title: 'Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
      - 'revert'
  - title: 'Chores'
    labels:
      - 'docs'
      - 'chore'
      - 'style'
      - 'build'
      - 'chores'
      - 'ci'
change-template:'- [ ] #$NUMBER $TITLE - @$AUTHOR $DESC '
template: |
  ## Changes

  $CHANGES
