name: module3_task2

on: # Events that trigger workflows
  push:
    branches: [master]
  schedule:
    # is a special character in YAML so you have to quote this string
    - cron: '30 00 * * *' # time 12:30 am

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: "Checkout" # Download code from the repository
        uses: actions/checkout@v3

      - name: "Run bash script"
        run: |
          cd module3_task2 && ./setup.sh

      - name: "Run make build" # Execute the command make build
        run: |
          cd module3_task2 && make build
      - name: "Run make target package" # Execute the command make package
        run: |
          cd module3_task2 && make package
      - name: "Run make target lint" # Should be updated to lint the files MD
        run: |
          cd module3_task2 && make lint
      - name: "Uni-Test" # Execute test
        run: |
          cd module3_task2 && make unit-tests
      - name: "Integration-tests" # Execute integration-tests
        run: |
          cd module3_task2 && make integration-tests
      - name: "Archive production artifacts"
        uses: actions/upload-artifact@master
        with:
          name: file named awesome-website
          path: |
            module3_task2/awesome-website.zip
